### ISSUE TITLE
When I set the width and height for img, the image disappeared when I printed it

### ISSUE THREAD

**Issue by EnochGao** [vivliostyle/vivliostyle-print#11]
https://vivliostyle.github.io/vivliostyle-print

[demo.txt](https://github.com/vivliostyle/vivliostyle-print/files/15257467/demo.txt)

![image](https://github.com/vivliostyle/vivliostyle-print/assets/41459067/af70f379-c481-4dcb-8b91-993c83c06c33)

**Comment by EnochGao** [comment]
I carried out the following implementation with reference to printing myself.
[print source code](https://github.com/vivliostyle/vivliostyle.js/blob/master/packages/core/src/vivliostyle/print.ts)

![image](https://github.com/vivliostyle/vivliostyle-print/assets/41459067/047aca28-a954-4cfc-a4b7-86da743d8fcb)

**Comment by MurakamiShinyu** [comment]
Resolved in https://github.com/vivliostyle/vivliostyle.js/pull/1340
