### ISSUE TITLE
Old resource files are included in the npm package

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle-print#7]
I checked the files included in the `@vivliostyle/print` npm package:
```
$ tree node_modules/@vivliostyle/print/ 
node_modules/@vivliostyle/print/
├── CONTRIBUTING.md
├── LICENSE
├── README.md
├── demo
│   ├── index.html
│   └── index.js
├── dist
│   ├── index.cjs.js
│   ├── index.cjs.js.map
│   ├── index.es6.js
│   ├── index.es6.js.map
│   └── resources
│       ├── favicon.ico
│       ├── mathjax-config.js
│       ├── user-agent-base.css
│       ├── user-agent-page.css
│       ├── user-agent.xml
│       ├── validation.txt
│       ├── vivliostyle-viewport-screen.css
│       └── vivliostyle-viewport.css
├── package.json
├── rollup.config.js
├── rollup.demo.config.js
└── src
    └── index.js

4 directories, 21 files
```

I found the `dist/resources/*` files are from old vivliostyle.js version, and these files should not be needed in the current version.
It seems that the old files remained when it was built.

Also these old `resources` files are found in the gh-pages branch of this repository:
https://github.com/vivliostyle/vivliostyle-print/tree/gh-pages/resources

There should be no problem deleting these files.

(@johanneswilm please check this and make v2.4.0)

**Comment by johanneswilm** [comment]
@MurakamiShinyu Done. Nice work on 2.4.0! I've added the method to the demo.
